
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(688, 829)
        MainWindow.setStyleSheet("")
        MainWindow.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        MainWindow.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 540, 721))
        self.label.setStyleSheet("background-color: rgb(40,36,46);\n"
"border-radius:50px;\n"
"")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(200, 10, 141, 51))
        self.label_10.setStyleSheet("border-image: url(:/logo/logo.png);\n"
"")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 70, 540, 111))
        self.label_2.setStyleSheet("background-color: rgb(53,48,61);\n"
"border-radius:50px;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.LoginIGmainLabel = QtWidgets.QLabel(self.centralwidget)
        self.LoginIGmainLabel.setGeometry(QtCore.QRect(210, 80, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.LoginIGmainLabel.setFont(font)
        self.LoginIGmainLabel.setStyleSheet("color: rgb(255, 255, 255);")
        self.LoginIGmainLabel.setObjectName("LoginIGmainLabel")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(126, 140, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(126, 110, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.passwordEntry = QtWidgets.QLineEdit(self.centralwidget)
        self.passwordEntry.setGeometry(QtCore.QRect(190, 140, 161, 20))
        self.passwordEntry.setStyleSheet("background-color: rgb(79,74,84);\n"
"color: rgb(255, 255, 255);\n"
"border:none;\n"
"border-radius:10px;\n"
"\n"
"")
        self.passwordEntry.setText("")
        self.passwordEntry.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordEntry.setObjectName("passwordEntry")
        self.loginEntry = QtWidgets.QLineEdit(self.centralwidget)
        self.loginEntry.setGeometry(QtCore.QRect(190, 110, 161, 20))
        self.loginEntry.setStyleSheet("background-color: rgb(79,74,84);\n"
"color: rgb(255, 255, 255);\n"
"border:none;\n"
"border-radius:10px;\n"
"\n"
"")
        self.loginEntry.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.loginEntry.setPlaceholderText("")
        self.loginEntry.setObjectName("loginEntry")
        self.saveButton = QtWidgets.QToolButton(self.centralwidget)
        self.saveButton.setGeometry(QtCore.QRect(390, 80, 81, 23))
        self.saveButton.setStyleSheet("border-radius:5px;\n"
"background-color: rgb(79, 74, 84);\n"
"color: rgb(255, 255, 255);")
        self.saveButton.setObjectName("saveButton")
        self.loadButton = QtWidgets.QToolButton(self.centralwidget)
        self.loadButton.setGeometry(QtCore.QRect(390, 110, 81, 23))
        self.loadButton.setStyleSheet("border-radius:5px;\n"
"background-color: rgb(79, 74, 84);\n"
"color: rgb(255, 255, 255);")
        self.loadButton.setObjectName("loadButton")
        self.delButton = QtWidgets.QToolButton(self.centralwidget)
        self.delButton.setGeometry(QtCore.QRect(390, 140, 81, 23))
        self.delButton.setStyleSheet("border-radius:5px;\n"
"background-color: rgb(79, 74, 84);\n"
"color: rgb(255, 255, 255);")
        self.delButton.setObjectName("delButton")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(0, 185, 540, 101))
        self.label_6.setStyleSheet("background-color: rgb(53,48,61);\n"
"border-radius:50px;")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.IloscKontEntry = QtWidgets.QLineEdit(self.centralwidget)
        self.IloscKontEntry.setGeometry(QtCore.QRect(110, 250, 161, 20))
        self.IloscKontEntry.setStyleSheet("background-color: rgb(79,74,84);\n"
"color: rgb(255, 255, 255);\n"
"border:none;\n"
"border-radius:10px;\n"
"\n"
"")
        self.IloscKontEntry.setMaxLength(100)
        self.IloscKontEntry.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.IloscKontEntry.setDragEnabled(False)
        self.IloscKontEntry.setObjectName("IloscKontEntry")
        self.FollowersButton = QtWidgets.QToolButton(self.centralwidget)
        self.FollowersButton.setGeometry(QtCore.QRect(295, 250, 141, 23))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(79, 74, 84))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(79, 74, 84))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(79, 74, 84))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(79, 74, 84))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(79, 74, 84))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(79, 74, 84))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(79, 74, 84))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(79, 74, 84))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(79, 74, 84))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.FollowersButton.setPalette(palette)
        self.FollowersButton.setStyleSheet("border-radius:5px;\n"
"background-color: rgb(79, 74, 84);\n"
"color: rgb(255, 255, 255);")
        self.FollowersButton.setObjectName("FollowersButton")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(20, 220, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(20, 250, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_8.setObjectName("label_8")
        self.LoginIGmainLabel_2 = QtWidgets.QLabel(self.centralwidget)
        self.LoginIGmainLabel_2.setGeometry(QtCore.QRect(200, 190, 141, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.LoginIGmainLabel_2.setFont(font)
        self.LoginIGmainLabel_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.LoginIGmainLabel_2.setObjectName("LoginIGmainLabel_2")
        self.NazwaKontaEntry = QtWidgets.QLineEdit(self.centralwidget)
        self.NazwaKontaEntry.setEnabled(True)
        self.NazwaKontaEntry.setGeometry(QtCore.QRect(110, 220, 161, 20))
        self.NazwaKontaEntry.setStyleSheet("background-color: rgb(79,74,84);\n"
"color: rgb(255, 255, 255);\n"
"border: none;\n"
"border-radius:10px;\n"
"\n"
"")
        self.NazwaKontaEntry.setPlaceholderText("")
        self.NazwaKontaEntry.setObjectName("NazwaKontaEntry")
        self.label_26 = QtWidgets.QLabel(self.centralwidget)
        self.label_26.setGeometry(QtCore.QRect(290, 220, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_26.setFont(font)
        self.label_26.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_26.setObjectName("label_26")
        self.DownloadedLabel = QtWidgets.QLabel(self.centralwidget)
        self.DownloadedLabel.setGeometry(QtCore.QRect(440, 220, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.DownloadedLabel.setFont(font)
        self.DownloadedLabel.setStyleSheet("color: rgb(255, 255, 255);")
        self.DownloadedLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.DownloadedLabel.setObjectName("DownloadedLabel")
        self.Ver = QtWidgets.QLabel(self.centralwidget)
        self.Ver.setGeometry(QtCore.QRect(20, 20, 51, 16))
        self.Ver.setStyleSheet("border-radius:5px;\n"
"background-color: rgb(79, 74, 84);\n"
"color: rgb(255, 255, 255);")
        self.Ver.setAlignment(QtCore.Qt.AlignCenter)
        self.Ver.setObjectName("Ver")
        self.CloseButton = QtWidgets.QToolButton(self.centralwidget)
        self.CloseButton.setGeometry(QtCore.QRect(480, 20, 16, 16))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(7)
        font.setBold(False)
        font.setWeight(50)
        self.CloseButton.setFont(font)
        self.CloseButton.setToolTipDuration(1)
        self.CloseButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.CloseButton.setStyleSheet("background-color: rgb(255, 96, 92);\n"
"image: url(:/clos/close.png);\n"
"border-radius:8px;\n"
"")
        self.CloseButton.setText("")
        self.CloseButton.setIconSize(QtCore.QSize(25, 25))
        self.CloseButton.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.CloseButton.setAutoRaise(False)
        self.CloseButton.setObjectName("CloseButton")
        self.minimaliseButton = QtWidgets.QToolButton(self.centralwidget)
        self.minimaliseButton.setGeometry(QtCore.QRect(460, 20, 16, 16))
        self.minimaliseButton.setStyleSheet("background-color: rgb(255, 189, 68);\n"
"image: url(:/min/minimize.png);\n"
"border-radius:8px;\n"
"")
        self.minimaliseButton.setText("")
        self.minimaliseButton.setIconSize(QtCore.QSize(25, 25))
        self.minimaliseButton.setObjectName("minimaliseButton")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(0, 290, 540, 150))
        self.label_15.setStyleSheet("background-color: rgb(53,48,61);\n"
"border-radius:50px;")
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        self.minFollow = QtWidgets.QLineEdit(self.centralwidget)
        self.minFollow.setGeometry(QtCore.QRect(110, 320, 31, 20))
        self.minFollow.setStyleSheet("background-color: rgb(79,74,84);\n"
"color: rgb(255, 255, 255);\n"
"border:none;\n"
"border-radius:10px;\n"
"\n"
"")
        self.minFollow.setText("")
        self.minFollow.setMaxLength(2)
        self.minFollow.setAlignment(QtCore.Qt.AlignCenter)
        self.minFollow.setObjectName("minFollow")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(20, 319, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_23.setObjectName("label_23")
        self.LikeCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.LikeCheckBox.setGeometry(QtCore.QRect(160, 350, 16, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.LikeCheckBox.setFont(font)
        self.LikeCheckBox.setStyleSheet("\n"
"color: rgb(255, 255, 255);")
        self.LikeCheckBox.setText("")
        self.LikeCheckBox.setIconSize(QtCore.QSize(20, 20))
        self.LikeCheckBox.setChecked(True)
        self.LikeCheckBox.setObjectName("LikeCheckBox")
        self.ComentCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.ComentCheckBox.setGeometry(QtCore.QRect(160, 380, 16, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ComentCheckBox.setFont(font)
        self.ComentCheckBox.setStyleSheet("color: rgb(255, 255, 255);")
        self.ComentCheckBox.setText("")
        self.ComentCheckBox.setIconSize(QtCore.QSize(20, 20))
        self.ComentCheckBox.setChecked(True)
        self.ComentCheckBox.setTristate(False)
        self.ComentCheckBox.setObjectName("ComentCheckBox")
        self.LoginIGmainLabel_4 = QtWidgets.QLabel(self.centralwidget)
        self.LoginIGmainLabel_4.setGeometry(QtCore.QRect(210, 290, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.LoginIGmainLabel_4.setFont(font)
        self.LoginIGmainLabel_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.LoginIGmainLabel_4.setObjectName("LoginIGmainLabel_4")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(20, 350, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_17.setObjectName("label_17")
        self.maxFollow = QtWidgets.QLineEdit(self.centralwidget)
        self.maxFollow.setGeometry(QtCore.QRect(150, 320, 31, 20))
        self.maxFollow.setStyleSheet("background-color: rgb(79,74,84);\n"
"color: rgb(255, 255, 255);\n"
"border:none;\n"
"border-radius:10px;\n"
"\n"
"")
        self.maxFollow.setText("")
        self.maxFollow.setMaxLength(2)
        self.maxFollow.setAlignment(QtCore.Qt.AlignCenter)
        self.maxFollow.setObjectName("maxFollow")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(20, 380, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_16.setObjectName("label_16")
        self.FollowButton = QtWidgets.QToolButton(self.centralwidget)
        self.FollowButton.setGeometry(QtCore.QRect(265, 410, 121, 23))
        self.FollowButton.setStyleSheet("border-radius:5px;\n"
"background-color: rgb(79, 74, 84);\n"
"color: rgb(255, 255, 255);")
        self.FollowButton.setObjectName("FollowButton")
        self.followCountLabel = QtWidgets.QLabel(self.centralwidget)
        self.followCountLabel.setGeometry(QtCore.QRect(455, 320, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.followCountLabel.setFont(font)
        self.followCountLabel.setStyleSheet("color: rgb(255, 255, 255);")
        self.followCountLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.followCountLabel.setObjectName("followCountLabel")
        self.label_28 = QtWidgets.QLabel(self.centralwidget)
        self.label_28.setGeometry(QtCore.QRect(290, 350, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_28.setFont(font)
        self.label_28.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_28.setObjectName("label_28")
        self.ComentLabel = QtWidgets.QLabel(self.centralwidget)
        self.ComentLabel.setGeometry(QtCore.QRect(455, 380, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ComentLabel.setFont(font)
        self.ComentLabel.setStyleSheet("color: rgb(255, 255, 255);")
        self.ComentLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ComentLabel.setObjectName("ComentLabel")
        self.label_25 = QtWidgets.QLabel(self.centralwidget)
        self.label_25.setGeometry(QtCore.QRect(290, 380, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_25.setFont(font)
        self.label_25.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_25.setObjectName("label_25")
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(290, 320, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_24.setFont(font)
        self.label_24.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_24.setObjectName("label_24")
        self.LikedPhotoLabel = QtWidgets.QLabel(self.centralwidget)
        self.LikedPhotoLabel.setGeometry(QtCore.QRect(455, 350, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.LikedPhotoLabel.setFont(font)
        self.LikedPhotoLabel.setStyleSheet("color: rgb(255, 255, 255);")
        self.LikedPhotoLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.LikedPhotoLabel.setObjectName("LikedPhotoLabel")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(0, 445, 540, 71))
        self.label_18.setStyleSheet("background-color: rgb(53,48,61);\n"
"border-radius:30px;")
        self.label_18.setText("")
        self.label_18.setObjectName("label_18")
        self.LoginIGmainLabel_7 = QtWidgets.QLabel(self.centralwidget)
        self.LoginIGmainLabel_7.setGeometry(QtCore.QRect(240, 450, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.LoginIGmainLabel_7.setFont(font)
        self.LoginIGmainLabel_7.setStyleSheet("color: rgb(255, 255, 255);")
        self.LoginIGmainLabel_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.LoginIGmainLabel_7.setFrameShadow(QtWidgets.QFrame.Plain)
        self.LoginIGmainLabel_7.setObjectName("LoginIGmainLabel_7")
        self.UnfollowButton = QtWidgets.QToolButton(self.centralwidget)
        self.UnfollowButton.setGeometry(QtCore.QRect(265, 475, 121, 23))
        self.UnfollowButton.setStyleSheet("border-radius:5px;\n"
"background-color: rgb(79, 74, 84);\n"
"color: rgb(255, 255, 255);")
        self.UnfollowButton.setObjectName("UnfollowButton")
        self.DodajKonto = QtWidgets.QToolButton(self.centralwidget)
        self.DodajKonto.setGeometry(QtCore.QRect(160, 475, 101, 23))
        self.DodajKonto.setStyleSheet("border-radius:5px;\n"
"background-color: rgb(79, 74, 84);\n"
"color: rgb(255, 255, 255);")
        self.DodajKonto.setObjectName("DodajKonto")
        self.CommentEdit = QtWidgets.QToolButton(self.centralwidget)
        self.CommentEdit.setGeometry(QtCore.QRect(160, 410, 101, 23))
        self.CommentEdit.setStyleSheet("border-radius:5px;\n"
"background-color: rgb(79, 74, 84);\n"
"color: rgb(255, 255, 255);")
        self.CommentEdit.setObjectName("CommentEdit")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(0, 695, 541, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("color: rgb(179, 179, 179);")
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(0, 520, 540, 171))
        self.label_9.setStyleSheet("background-color: rgb(53,48,61);\n"
"border-radius:50px;")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.LoginIGmainLabel_6 = QtWidgets.QLabel(self.centralwidget)
        self.LoginIGmainLabel_6.setGeometry(QtCore.QRect(230, 530, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.LoginIGmainLabel_6.setFont(font)
        self.LoginIGmainLabel_6.setStyleSheet("color: rgb(255, 255, 255);")
        self.LoginIGmainLabel_6.setObjectName("LoginIGmainLabel_6")
        self.label_29 = QtWidgets.QLabel(self.centralwidget)
        self.label_29.setGeometry(QtCore.QRect(20, 590, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_29.setFont(font)
        self.label_29.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_29.setObjectName("label_29")
        self.HowMuchDays = QtWidgets.QLabel(self.centralwidget)
        self.HowMuchDays.setGeometry(QtCore.QRect(120, 620, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.HowMuchDays.setFont(font)
        self.HowMuchDays.setStyleSheet("color: rgb(255, 255, 255);")
        self.HowMuchDays.setAlignment(QtCore.Qt.AlignCenter)
        self.HowMuchDays.setObjectName("HowMuchDays")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(120, 560, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("\n"
"color: rgb(123, 17, 58);")
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.label_30 = QtWidgets.QLabel(self.centralwidget)
        self.label_30.setGeometry(QtCore.QRect(20, 620, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_30.setFont(font)
        self.label_30.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_30.setObjectName("label_30")
        self.WhoIsLogin = QtWidgets.QLabel(self.centralwidget)
        self.WhoIsLogin.setGeometry(QtCore.QRect(120, 590, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.WhoIsLogin.setFont(font)
        self.WhoIsLogin.setStyleSheet("color: rgb(255, 255, 255);")
        self.WhoIsLogin.setAlignment(QtCore.Qt.AlignCenter)
        self.WhoIsLogin.setObjectName("WhoIsLogin")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(20, 560, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_19.setObjectName("label_19")
        self.Website = QtWidgets.QToolButton(self.centralwidget)
        self.Website.setGeometry(QtCore.QRect(230, 660, 81, 23))
        self.Website.setStyleSheet("border-radius:5px;\n"
"background-color: rgb(79, 74, 84);\n"
"color: rgb(255, 255, 255);")
        self.Website.setObjectName("Website")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(290, 560, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_22.setFont(font)
        self.label_22.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_22.setObjectName("label_22")
        self.timerLabel = QtWidgets.QLabel(self.centralwidget)
        self.timerLabel.setGeometry(QtCore.QRect(444, 560, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.timerLabel.setFont(font)
        self.timerLabel.setStyleSheet("color: rgb(255, 255, 255);")
        self.timerLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.timerLabel.setObjectName("timerLabel")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_10.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"justify\"><br/></p></body></html>"))
        self.LoginIGmainLabel.setText(_translate("MainWindow", "Dane do konta IG"))
        self.label_3.setText(_translate("MainWindow", "Hasło:"))
        self.label_4.setText(_translate("MainWindow", "Login:"))
        self.passwordEntry.setToolTip(_translate("MainWindow", "<html><head/><body><p>Podaj hasło do konta Instagram</p></body></html>"))
        self.loginEntry.setToolTip(_translate("MainWindow", "<html><head/><body><p>Podaj login do konta Instagram</p></body></html>"))
        self.saveButton.setText(_translate("MainWindow", "Zapisz Konto"))
        self.loadButton.setText(_translate("MainWindow", "Załaduj Konto"))
        self.delButton.setText(_translate("MainWindow", "Usuń Konto"))
        self.IloscKontEntry.setToolTip(_translate("MainWindow", "<html><head/><body><p>Ilość kont które bot ma pobrać</p></body></html>"))
        self.FollowersButton.setText(_translate("MainWindow", "Uruchom Pobieranie"))
        self.label_7.setText(_translate("MainWindow", "Nazwa Konta:"))
        self.label_8.setText(_translate("MainWindow", "Ilość kont:"))
        self.LoginIGmainLabel_2.setText(_translate("MainWindow", "Pobierz obserwatorów"))
        self.NazwaKontaEntry.setToolTip(_translate("MainWindow", "<html><head/><body><p>Nazwa Konta z którego bot ma wyciągnąć obserwujących</p></body></html>"))
        self.label_26.setText(_translate("MainWindow", "Pobranych Nazw Kont:"))
        self.DownloadedLabel.setText(_translate("MainWindow", "0"))
        self.Ver.setToolTip(_translate("MainWindow", "<html><head/><body><p>test</p></body></html>"))
        self.Ver.setText(_translate("MainWindow", "testowa"))
        self.minFollow.setToolTip(_translate("MainWindow", "<html><head/><body><p>Minimalna wartośc to 3</p></body></html>"))
        self.minFollow.setPlaceholderText(_translate("MainWindow", "Od"))
        self.label_23.setText(_translate("MainWindow", "Ilość Follow"))
        self.LoginIGmainLabel_4.setText(_translate("MainWindow", "Obserwacja z Pliku"))
        self.label_17.setText(_translate("MainWindow", "Polub zdjęcie"))
        self.maxFollow.setToolTip(_translate("MainWindow", "<html><head/><body><p>Maksymalna wartość to 30</p></body></html>"))
        self.maxFollow.setPlaceholderText(_translate("MainWindow", "Do"))
        self.label_16.setText(_translate("MainWindow", "Dodaj komentarz"))
        self.FollowButton.setText(_translate("MainWindow", "Uruchom Obserowanie"))
        self.followCountLabel.setText(_translate("MainWindow", "0"))
        self.label_28.setText(_translate("MainWindow", "Polubionych Zdjęć:"))
        self.ComentLabel.setText(_translate("MainWindow", "0"))
        self.label_25.setText(_translate("MainWindow", "Dodanych Komentarzy:"))
        self.label_24.setText(_translate("MainWindow", "Zaobserwowanych:"))
        self.LikedPhotoLabel.setText(_translate("MainWindow", "0"))
        self.LoginIGmainLabel_7.setText(_translate("MainWindow", "Unfollow"))
        self.UnfollowButton.setText(_translate("MainWindow", "Uruchom Unfollow"))
        self.DodajKonto.setToolTip(_translate("MainWindow", "<html><head/><body><p>Zapisz konta które bot ma pominąć</p></body></html>"))
        self.DodajKonto.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.DodajKonto.setText(_translate("MainWindow", "Zapisz Konta"))
        self.CommentEdit.setToolTip(_translate("MainWindow", "<html><head/><body><p>Edytuj komentarze które bot ma ummieszczać</p></body></html>"))
        self.CommentEdit.setText(_translate("MainWindow", "Edytuj Komentarze"))
        self.label_21.setText(_translate("MainWindow", "© Daniel Zieliński, Artur Kaczuba, Łukasz Mela 2021."))
        self.LoginIGmainLabel_6.setText(_translate("MainWindow", "Informacje"))
        self.label_29.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.label_29.setText(_translate("MainWindow", "Zalogowany:"))
        self.HowMuchDays.setText(_translate("MainWindow", "999 Dni"))
        self.label_20.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.label_20.setText(_translate("MainWindow", "Nieaktywny"))
        self.label_30.setText(_translate("MainWindow", "Pozostało:"))
        self.WhoIsLogin.setText(_translate("MainWindow", "TESTER"))
        self.label_19.setText(_translate("MainWindow", "Status:"))
        self.Website.setText(_translate("MainWindow", "Kontakt"))
        self.label_22.setText(_translate("MainWindow", "Następna sesja za:"))
        self.timerLabel.setText(_translate("MainWindow", "0s"))
class MainWindow(QtWidgets.QMainWindow):
    def __init__(self, parent=None):
        
        super(MainWindow, self).__init__(parent=parent)
        ui = Ui_MainWindow()
        ui.setupUi(self)
        ## BUTTONS ##
        ui.CloseButton.clicked.connect(self.close)
        ui.minimaliseButton.clicked.connect(self.minimized)
        
        who = ui.WhoIsLogin
        
    # Function
    def close(self):
        app.exit()

    def minimized(self):
        self.showMinimized()

    def mousePressEvent(self, event):  # +
        self.dragPos = event.globalPos()

    def mouseMoveEvent(self, event):  # !!!
        if event.buttons() == QtCore.Qt.LeftButton:
            self.move(self.pos() + event.globalPos() - self.dragPos)
            self.dragPos = event.globalPos()
            event.accept()

if __name__ == "__main__":
    import sys, res
    app = QtWidgets.QApplication(sys.argv)
    app.setQuitOnLastWindowClosed(False)
    w = MainWindow()
    w.show()
    sys.exit(app.exec_())

