from PyQt5 import QtCore, QtGui, QtWidgets

ver = "Beta v3.3"
verInfo = verInfo = "<p>Aktualizacja "+ver+":</p> <p>Informacje o poszczególnych polach</p><p>Zakres obserwacji Bota od 3 do 30</p>"

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(631, 875)
        MainWindow.setMinimumSize(QtCore.QSize(631, 875))
        MainWindow.setMaximumSize(QtCore.QSize(631, 875))
        MainWindow.setStyleSheet("")
        MainWindow.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        MainWindow.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 10, 611, 841))
        self.widget.setMinimumSize(QtCore.QSize(611, 841))
        self.widget.setMaximumSize(QtCore.QSize(611, 841))
        self.widget.setObjectName("widget")
        self.BG = QtWidgets.QLabel(self.widget)
        self.BG.setGeometry(QtCore.QRect(10, 0, 601, 841))
        self.BG.setMinimumSize(QtCore.QSize(601, 841))
        self.BG.setMaximumSize(QtCore.QSize(601, 841))
        self.BG.setStyleSheet("background-color: rgb(40,36,46);\n"
"border-radius:50px;\n"
"")
        self.BG.setText("")
        self.BG.setObjectName("BG")
        self.LoginIGmainLabel = QtWidgets.QLabel(self.widget)
        self.LoginIGmainLabel.setGeometry(QtCore.QRect(250, 60, 121, 16))
        self.LoginIGmainLabel.setMinimumSize(QtCore.QSize(121, 16))
        self.LoginIGmainLabel.setMaximumSize(QtCore.QSize(121, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.LoginIGmainLabel.setFont(font)
        self.LoginIGmainLabel.setStyleSheet("color: rgb(255, 255, 255);")
        self.LoginIGmainLabel.setObjectName("LoginIGmainLabel")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(20, 60, 580, 130))
        self.label.setMinimumSize(QtCore.QSize(580, 130))
        self.label.setMaximumSize(QtCore.QSize(580, 130))
        self.label.setStyleSheet("background-color: rgb(53,48,61);\n"
"border-radius:50px;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(126, 90, 51, 20))
        self.label_2.setMinimumSize(QtCore.QSize(51, 20))
        self.label_2.setMaximumSize(QtCore.QSize(51, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(126, 120, 51, 21))
        self.label_3.setMinimumSize(QtCore.QSize(51, 21))
        self.label_3.setMaximumSize(QtCore.QSize(51, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.loginEntry = QtWidgets.QLineEdit(self.widget)
        self.loginEntry.setGeometry(QtCore.QRect(180, 90, 161, 20))
        self.loginEntry.setMinimumSize(QtCore.QSize(161, 20))
        self.loginEntry.setMaximumSize(QtCore.QSize(161, 20))
        self.loginEntry.setStyleSheet("background-color: rgb(79,74,84);\n"
"color: rgb(255, 255, 255);\n"
"border:none;\n"
"border-radius:10px;\n"
"\n"
"")
        self.loginEntry.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.loginEntry.setPlaceholderText("")
        self.loginEntry.setObjectName("loginEntry")
        self.passwordEntry = QtWidgets.QLineEdit(self.widget)
        self.passwordEntry.setGeometry(QtCore.QRect(180, 120, 161, 20))
        self.passwordEntry.setMinimumSize(QtCore.QSize(161, 20))
        self.passwordEntry.setMaximumSize(QtCore.QSize(161, 20))
        self.passwordEntry.setStyleSheet("background-color: rgb(79,74,84);\n"
"color: rgb(255, 255, 255);\n"
"border:none;\n"
"border-radius:10px;\n"
"\n"
"")
        self.passwordEntry.setText("")
        self.passwordEntry.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordEntry.setObjectName("passwordEntry")
        self.saveButton = QtWidgets.QToolButton(self.widget)
        self.saveButton.setGeometry(QtCore.QRect(180, 150, 81, 23))
        self.saveButton.setMinimumSize(QtCore.QSize(81, 23))
        self.saveButton.setMaximumSize(QtCore.QSize(81, 23))
        self.saveButton.setStyleSheet("border-radius:5px;\n"
"background-color: rgb(79, 74, 84);\n"
"color: rgb(255, 255, 255);")
        self.saveButton.setObjectName("saveButton")
        self.loadButton = QtWidgets.QToolButton(self.widget)
        self.loadButton.setGeometry(QtCore.QRect(270, 150, 81, 23))
        self.loadButton.setMinimumSize(QtCore.QSize(81, 23))
        self.loadButton.setMaximumSize(QtCore.QSize(81, 23))
        self.loadButton.setStyleSheet("border-radius:5px;\n"
"background-color: rgb(79, 74, 84);\n"
"color: rgb(255, 255, 255);")
        self.loadButton.setObjectName("loadButton")
        self.delButton = QtWidgets.QToolButton(self.widget)
        self.delButton.setGeometry(QtCore.QRect(360, 150, 81, 23))
        self.delButton.setMinimumSize(QtCore.QSize(81, 23))
        self.delButton.setMaximumSize(QtCore.QSize(81, 23))
        self.delButton.setStyleSheet("border-radius:5px;\n"
"background-color: rgb(79, 74, 84);\n"
"color: rgb(255, 255, 255);")
        self.delButton.setObjectName("delButton")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(435, 86, 51, 20))
        self.label_4.setMinimumSize(QtCore.QSize(51, 20))
        self.label_4.setMaximumSize(QtCore.QSize(51, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(435, 116, 51, 21))
        self.label_5.setMinimumSize(QtCore.QSize(51, 21))
        self.label_5.setMaximumSize(QtCore.QSize(51, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.FirefoxButton = QtWidgets.QRadioButton(self.widget)
        self.FirefoxButton.setGeometry(QtCore.QRect(490, 90, 16, 17))
        self.FirefoxButton.setMinimumSize(QtCore.QSize(16, 17))
        self.FirefoxButton.setMaximumSize(QtCore.QSize(16, 17))
        self.FirefoxButton.setText("")
        self.FirefoxButton.setObjectName("FirefoxButton")
        self.Chromebutton = QtWidgets.QRadioButton(self.widget)
        self.Chromebutton.setGeometry(QtCore.QRect(490, 120, 21, 16))
        self.Chromebutton.setMinimumSize(QtCore.QSize(21, 16))
        self.Chromebutton.setMaximumSize(QtCore.QSize(21, 16))
        self.Chromebutton.setText("")
        self.Chromebutton.setChecked(True)
        self.Chromebutton.setObjectName("Chromebutton")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setGeometry(QtCore.QRect(20, 200, 290, 130))
        self.label_6.setMinimumSize(QtCore.QSize(290, 130))
        self.label_6.setMaximumSize(QtCore.QSize(290, 130))
        self.label_6.setStyleSheet("background-color: rgb(53,48,61);\n"
"border-radius:50px;")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.LoginIGmainLabel_2 = QtWidgets.QLabel(self.widget)
        self.LoginIGmainLabel_2.setGeometry(QtCore.QRect(70, 210, 191, 20))
        self.LoginIGmainLabel_2.setMinimumSize(QtCore.QSize(191, 20))
        self.LoginIGmainLabel_2.setMaximumSize(QtCore.QSize(191, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.LoginIGmainLabel_2.setFont(font)
        self.LoginIGmainLabel_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.LoginIGmainLabel_2.setObjectName("LoginIGmainLabel_2")
        self.IloscKontEntry = QtWidgets.QLineEdit(self.widget)
        self.IloscKontEntry.setGeometry(QtCore.QRect(130, 270, 170, 20))
        self.IloscKontEntry.setMinimumSize(QtCore.QSize(170, 20))
        self.IloscKontEntry.setMaximumSize(QtCore.QSize(170, 20))
        self.IloscKontEntry.setStyleSheet("background-color: rgb(79,74,84);\n"
"color: rgb(255, 255, 255);\n"
"border:none;\n"
"border-radius:10px;\n"
"\n"
"")
        self.IloscKontEntry.setMaxLength(100)
        self.IloscKontEntry.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.IloscKontEntry.setDragEnabled(False)
        self.IloscKontEntry.setObjectName("IloscKontEntry")
        self.NazwaKontaEntry = QtWidgets.QLineEdit(self.widget)
        self.NazwaKontaEntry.setEnabled(True)
        self.NazwaKontaEntry.setGeometry(QtCore.QRect(130, 240, 170, 20))
        self.NazwaKontaEntry.setMinimumSize(QtCore.QSize(170, 20))
        self.NazwaKontaEntry.setMaximumSize(QtCore.QSize(170, 20))
        self.NazwaKontaEntry.setStyleSheet("background-color: rgb(79,74,84);\n"
"color: rgb(255, 255, 255);\n"
"border: none;\n"
"border-radius:10px;\n"
"\n"
"")
        self.NazwaKontaEntry.setPlaceholderText("")
        self.NazwaKontaEntry.setObjectName("NazwaKontaEntry")
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setGeometry(QtCore.QRect(30, 240, 81, 20))
        self.label_7.setMinimumSize(QtCore.QSize(81, 20))
        self.label_7.setMaximumSize(QtCore.QSize(81, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setGeometry(QtCore.QRect(30, 270, 81, 21))
        self.label_8.setMinimumSize(QtCore.QSize(81, 21))
        self.label_8.setMaximumSize(QtCore.QSize(81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_8.setObjectName("label_8")
        self.FollowersButton = QtWidgets.QToolButton(self.widget)
        self.FollowersButton.setGeometry(QtCore.QRect(95, 300, 141, 23))
        self.FollowersButton.setMinimumSize(QtCore.QSize(141, 23))
        self.FollowersButton.setMaximumSize(QtCore.QSize(141, 23))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(79, 74, 84))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(79, 74, 84))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(79, 74, 84))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(79, 74, 84))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(79, 74, 84))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(79, 74, 84))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(79, 74, 84))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(79, 74, 84))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(79, 74, 84))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.FollowersButton.setPalette(palette)
        self.FollowersButton.setStyleSheet("border-radius:5px;\n"
"background-color: rgb(79, 74, 84);\n"
"color: rgb(255, 255, 255);")
        self.FollowersButton.setObjectName("FollowersButton")
        self.label_11 = QtWidgets.QLabel(self.widget)
        self.label_11.setGeometry(QtCore.QRect(310, 200, 290, 131))
        self.label_11.setMinimumSize(QtCore.QSize(290, 131))
        self.label_11.setMaximumSize(QtCore.QSize(290, 131))
        self.label_11.setStyleSheet("background-color: rgb(53,48,61);\n"
"border-radius:50px;")
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.NazwaHaszEntry = QtWidgets.QLineEdit(self.widget)
        self.NazwaHaszEntry.setGeometry(QtCore.QRect(400, 240, 170, 20))
        self.NazwaHaszEntry.setMinimumSize(QtCore.QSize(170, 20))
        self.NazwaHaszEntry.setMaximumSize(QtCore.QSize(170, 20))
        self.NazwaHaszEntry.setStyleSheet("background-color: rgb(79,74,84);\n"
"color: rgb(255, 255, 255);\n"
"border:none;\n"
"border-radius:10px;\n"
"\n"
"")
        self.NazwaHaszEntry.setPlaceholderText("")
        self.NazwaHaszEntry.setObjectName("NazwaHaszEntry")
        self.HaszButton = QtWidgets.QToolButton(self.widget)
        self.HaszButton.setGeometry(QtCore.QRect(390, 300, 141, 23))
        self.HaszButton.setMinimumSize(QtCore.QSize(141, 23))
        self.HaszButton.setMaximumSize(QtCore.QSize(141, 23))
        self.HaszButton.setStyleSheet("border-radius:5px;\n"
"background-color: rgb(79, 74, 84);\n"
"color: rgb(255, 255, 255);")
        self.HaszButton.setObjectName("HaszButton")
        self.LoginIGmainLabel_3 = QtWidgets.QLabel(self.widget)
        self.LoginIGmainLabel_3.setGeometry(QtCore.QRect(395, 210, 131, 20))
        self.LoginIGmainLabel_3.setMinimumSize(QtCore.QSize(131, 20))
        self.LoginIGmainLabel_3.setMaximumSize(QtCore.QSize(131, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.LoginIGmainLabel_3.setFont(font)
        self.LoginIGmainLabel_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.LoginIGmainLabel_3.setObjectName("LoginIGmainLabel_3")
        self.label_12 = QtWidgets.QLabel(self.widget)
        self.label_12.setGeometry(QtCore.QRect(320, 240, 71, 20))
        self.label_12.setMinimumSize(QtCore.QSize(71, 20))
        self.label_12.setMaximumSize(QtCore.QSize(71, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.widget)
        self.label_13.setGeometry(QtCore.QRect(320, 270, 81, 21))
        self.label_13.setMinimumSize(QtCore.QSize(81, 21))
        self.label_13.setMaximumSize(QtCore.QSize(81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_13.setObjectName("label_13")
        self.IloscHaszKont = QtWidgets.QLineEdit(self.widget)
        self.IloscHaszKont.setGeometry(QtCore.QRect(400, 270, 170, 20))
        self.IloscHaszKont.setMinimumSize(QtCore.QSize(170, 20))
        self.IloscHaszKont.setMaximumSize(QtCore.QSize(170, 20))
        self.IloscHaszKont.setStyleSheet("background-color: rgb(79,74,84);\n"
"color: rgb(255, 255, 255);\n"
"border:none;\n"
"border-radius:10px;\n"
"\n"
"")
        self.IloscHaszKont.setMaxLength(100)
        self.IloscHaszKont.setPlaceholderText("")
        self.IloscHaszKont.setObjectName("IloscHaszKont")
        self.label_15 = QtWidgets.QLabel(self.widget)
        self.label_15.setGeometry(QtCore.QRect(20, 340, 290, 161))
        self.label_15.setMinimumSize(QtCore.QSize(290, 161))
        self.label_15.setMaximumSize(QtCore.QSize(290, 161))
        self.label_15.setStyleSheet("background-color: rgb(53,48,61);\n"
"border-radius:50px;")
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        self.LoginIGmainLabel_4 = QtWidgets.QLabel(self.widget)
        self.LoginIGmainLabel_4.setGeometry(QtCore.QRect(100, 350, 131, 20))
        self.LoginIGmainLabel_4.setMinimumSize(QtCore.QSize(131, 20))
        self.LoginIGmainLabel_4.setMaximumSize(QtCore.QSize(131, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.LoginIGmainLabel_4.setFont(font)
        self.LoginIGmainLabel_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.LoginIGmainLabel_4.setObjectName("LoginIGmainLabel_4")
        self.ComentCheckBox = QtWidgets.QCheckBox(self.widget)
        self.ComentCheckBox.setGeometry(QtCore.QRect(190, 380, 16, 17))
        self.ComentCheckBox.setMinimumSize(QtCore.QSize(16, 17))
        self.ComentCheckBox.setMaximumSize(QtCore.QSize(16, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ComentCheckBox.setFont(font)
        self.ComentCheckBox.setStyleSheet("color: rgb(255, 255, 255);border-radus:5px;")
        self.ComentCheckBox.setText("")
        self.ComentCheckBox.setIconSize(QtCore.QSize(20, 20))
        self.ComentCheckBox.setChecked(True)
        self.ComentCheckBox.setTristate(False)
        self.ComentCheckBox.setObjectName("ComentCheckBox")
        self.LikeCheckBox = QtWidgets.QCheckBox(self.widget)
        self.LikeCheckBox.setGeometry(QtCore.QRect(190, 400, 16, 21))
        self.LikeCheckBox.setMinimumSize(QtCore.QSize(16, 21))
        self.LikeCheckBox.setMaximumSize(QtCore.QSize(16, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.LikeCheckBox.setFont(font)
        self.LikeCheckBox.setStyleSheet("color: rgb(255, 255, 255);")
        self.LikeCheckBox.setText("")
        self.LikeCheckBox.setIconSize(QtCore.QSize(20, 20))
        self.LikeCheckBox.setChecked(True)
        self.LikeCheckBox.setObjectName("LikeCheckBox")
        self.label_16 = QtWidgets.QLabel(self.widget)
        self.label_16.setGeometry(QtCore.QRect(50, 380, 101, 20))
        self.label_16.setMinimumSize(QtCore.QSize(101, 20))
        self.label_16.setMaximumSize(QtCore.QSize(101, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.widget)
        self.label_17.setGeometry(QtCore.QRect(50, 400, 81, 21))
        self.label_17.setMinimumSize(QtCore.QSize(81, 21))
        self.label_17.setMaximumSize(QtCore.QSize(81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_17.setObjectName("label_17")
        self.FollowButton = QtWidgets.QToolButton(self.widget)
        self.FollowButton.setGeometry(QtCore.QRect(90, 460, 141, 23))
        self.FollowButton.setMinimumSize(QtCore.QSize(141, 23))
        self.FollowButton.setMaximumSize(QtCore.QSize(141, 23))
        self.FollowButton.setStyleSheet("border-radius:5px;\n"
"background-color: rgb(79, 74, 84);\n"
"color: rgb(255, 255, 255);")
        self.FollowButton.setObjectName("FollowButton")
        self.label_18 = QtWidgets.QLabel(self.widget)
        self.label_18.setGeometry(QtCore.QRect(310, 340, 290, 161))
        self.label_18.setMinimumSize(QtCore.QSize(290, 161))
        self.label_18.setMaximumSize(QtCore.QSize(290, 161))
        self.label_18.setStyleSheet("background-color: rgb(53,48,61);\n"
"border-radius:50px;")
        self.label_18.setText("")
        self.label_18.setObjectName("label_18")
        self.LoginIGmainLabel_5 = QtWidgets.QLabel(self.widget)
        self.LoginIGmainLabel_5.setGeometry(QtCore.QRect(400, 350, 121, 20))
        self.LoginIGmainLabel_5.setMinimumSize(QtCore.QSize(121, 20))
        self.LoginIGmainLabel_5.setMaximumSize(QtCore.QSize(121, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.LoginIGmainLabel_5.setFont(font)
        self.LoginIGmainLabel_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.LoginIGmainLabel_5.setObjectName("LoginIGmainLabel_5")
        self.Message_Button = QtWidgets.QToolButton(self.widget)
        self.Message_Button.setGeometry(QtCore.QRect(390, 380, 141, 23))
        self.Message_Button.setMinimumSize(QtCore.QSize(141, 23))
        self.Message_Button.setMaximumSize(QtCore.QSize(141, 23))
        self.Message_Button.setStyleSheet("border-radius:5px;\n"
"background-color: rgb(79, 74, 84);\n"
"color: rgb(255, 255, 255);")
        self.Message_Button.setObjectName("Message_Button")
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setGeometry(QtCore.QRect(20, 510, 580, 294))
        self.label_9.setMinimumSize(QtCore.QSize(580, 294))
        self.label_9.setMaximumSize(QtCore.QSize(580, 294))
        self.label_9.setStyleSheet("background-color: rgb(53,48,61);\n"
"border-radius:50px;")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.LoginIGmainLabel_6 = QtWidgets.QLabel(self.widget)
        self.LoginIGmainLabel_6.setGeometry(QtCore.QRect(265, 520, 91, 16))
        self.LoginIGmainLabel_6.setMinimumSize(QtCore.QSize(91, 16))
        self.LoginIGmainLabel_6.setMaximumSize(QtCore.QSize(91, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.LoginIGmainLabel_6.setFont(font)
        self.LoginIGmainLabel_6.setStyleSheet("color: rgb(255, 255, 255);")
        self.LoginIGmainLabel_6.setObjectName("LoginIGmainLabel_6")
        self.label_19 = QtWidgets.QLabel(self.widget)
        self.label_19.setGeometry(QtCore.QRect(30, 550, 81, 20))
        self.label_19.setMinimumSize(QtCore.QSize(81, 20))
        self.label_19.setMaximumSize(QtCore.QSize(81, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_19.setObjectName("label_19")
        self.label_10 = QtWidgets.QLabel(self.widget)
        self.label_10.setGeometry(QtCore.QRect(240, 0, 141, 51))
        self.label_10.setMinimumSize(QtCore.QSize(141, 51))
        self.label_10.setMaximumSize(QtCore.QSize(141, 51))
        self.label_10.setStyleSheet("border-image: url(:/logo/logo white bez tla.png);")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.label_20 = QtWidgets.QLabel(self.widget)
        self.label_20.setGeometry(QtCore.QRect(120, 550, 91, 20))
        self.label_20.setMinimumSize(QtCore.QSize(91, 20))
        self.label_20.setMaximumSize(QtCore.QSize(91, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("\n"
"color: rgb(123, 17, 58);")
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.CommentEdit = QtWidgets.QToolButton(self.widget)
        self.CommentEdit.setGeometry(QtCore.QRect(390, 771, 141, 23))
        self.CommentEdit.setMinimumSize(QtCore.QSize(141, 23))
        self.CommentEdit.setMaximumSize(QtCore.QSize(141, 23))
        self.CommentEdit.setStyleSheet("border-radius:5px;\n"
"background-color: rgb(79, 74, 84);\n"
"color: rgb(255, 255, 255);")
        self.CommentEdit.setObjectName("CommentEdit")
        self.MessageEdit = QtWidgets.QToolButton(self.widget)
        self.MessageEdit.setGeometry(QtCore.QRect(240, 771, 141, 23))
        self.MessageEdit.setMinimumSize(QtCore.QSize(141, 23))
        self.MessageEdit.setMaximumSize(QtCore.QSize(141, 23))
        self.MessageEdit.setStyleSheet("border-radius:5px;\n"
"background-color: rgb(79, 74, 84);\n"
"color: rgb(255, 255, 255);")
        self.MessageEdit.setObjectName("MessageEdit")
        self.Website = QtWidgets.QToolButton(self.widget)
        self.Website.setGeometry(QtCore.QRect(90, 771, 141, 23))
        self.Website.setMinimumSize(QtCore.QSize(141, 23))
        self.Website.setMaximumSize(QtCore.QSize(141, 23))
        self.Website.setStyleSheet("border-radius:5px;\n"
"background-color: rgb(79, 74, 84);\n"
"color: rgb(255, 255, 255);")
        self.Website.setObjectName("Website")
        self.label_21 = QtWidgets.QLabel(self.widget)
        self.label_21.setGeometry(QtCore.QRect(80, 810, 461, 20))
        self.label_21.setMinimumSize(QtCore.QSize(461, 20))
        self.label_21.setMaximumSize(QtCore.QSize(461, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("color: rgb(179, 179, 179);")
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.widget)
        self.label_22.setGeometry(QtCore.QRect(305, 550, 181, 20))
        self.label_22.setMinimumSize(QtCore.QSize(181, 20))
        self.label_22.setMaximumSize(QtCore.QSize(181, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_22.setFont(font)
        self.label_22.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_22.setObjectName("label_22")
        self.timerLabel = QtWidgets.QLabel(self.widget)
        self.timerLabel.setGeometry(QtCore.QRect(495, 550, 41, 20))
        self.timerLabel.setMinimumSize(QtCore.QSize(41, 20))
        self.timerLabel.setMaximumSize(QtCore.QSize(41, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.timerLabel.setFont(font)
        self.timerLabel.setStyleSheet("color: rgb(255, 255, 255);")
        self.timerLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.timerLabel.setObjectName("timerLabel")
        self.label_24 = QtWidgets.QLabel(self.widget)
        self.label_24.setGeometry(QtCore.QRect(305, 580, 181, 20))
        self.label_24.setMinimumSize(QtCore.QSize(181, 20))
        self.label_24.setMaximumSize(QtCore.QSize(181, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_24.setFont(font)
        self.label_24.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_24.setObjectName("label_24")
        self.followCountLabel = QtWidgets.QLabel(self.widget)
        self.followCountLabel.setGeometry(QtCore.QRect(495, 580, 41, 20))
        self.followCountLabel.setMinimumSize(QtCore.QSize(41, 20))
        self.followCountLabel.setMaximumSize(QtCore.QSize(41, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.followCountLabel.setFont(font)
        self.followCountLabel.setStyleSheet("color: rgb(255, 255, 255);")
        self.followCountLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.followCountLabel.setObjectName("followCountLabel")
        self.label_26 = QtWidgets.QLabel(self.widget)
        self.label_26.setGeometry(QtCore.QRect(305, 670, 181, 20))
        self.label_26.setMinimumSize(QtCore.QSize(181, 20))
        self.label_26.setMaximumSize(QtCore.QSize(181, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_26.setFont(font)
        self.label_26.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_26.setObjectName("label_26")
        self.DownloadedLabel = QtWidgets.QLabel(self.widget)
        self.DownloadedLabel.setGeometry(QtCore.QRect(495, 670, 41, 20))
        self.DownloadedLabel.setMinimumSize(QtCore.QSize(41, 20))
        self.DownloadedLabel.setMaximumSize(QtCore.QSize(41, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.DownloadedLabel.setFont(font)
        self.DownloadedLabel.setStyleSheet("color: rgb(255, 255, 255);")
        self.DownloadedLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.DownloadedLabel.setObjectName("DownloadedLabel")
        self.label_27 = QtWidgets.QLabel(self.widget)
        self.label_27.setGeometry(QtCore.QRect(305, 700, 181, 20))
        self.label_27.setMinimumSize(QtCore.QSize(181, 20))
        self.label_27.setMaximumSize(QtCore.QSize(181, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_27.setFont(font)
        self.label_27.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_27.setObjectName("label_27")
        self.SendedMessage = QtWidgets.QLabel(self.widget)
        self.SendedMessage.setGeometry(QtCore.QRect(495, 700, 41, 20))
        self.SendedMessage.setMinimumSize(QtCore.QSize(41, 20))
        self.SendedMessage.setMaximumSize(QtCore.QSize(41, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.SendedMessage.setFont(font)
        self.SendedMessage.setStyleSheet("color: rgb(255, 255, 255);")
        self.SendedMessage.setAlignment(QtCore.Qt.AlignCenter)
        self.SendedMessage.setObjectName("SendedMessage")
        self.label_25 = QtWidgets.QLabel(self.widget)
        self.label_25.setGeometry(QtCore.QRect(305, 640, 181, 20))
        self.label_25.setMinimumSize(QtCore.QSize(181, 20))
        self.label_25.setMaximumSize(QtCore.QSize(181, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_25.setFont(font)
        self.label_25.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_25.setObjectName("label_25")
        self.label_28 = QtWidgets.QLabel(self.widget)
        self.label_28.setGeometry(QtCore.QRect(305, 610, 181, 20))
        self.label_28.setMinimumSize(QtCore.QSize(181, 20))
        self.label_28.setMaximumSize(QtCore.QSize(181, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_28.setFont(font)
        self.label_28.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_28.setObjectName("label_28")
        self.LikedPhotoLabel = QtWidgets.QLabel(self.widget)
        self.LikedPhotoLabel.setGeometry(QtCore.QRect(495, 610, 41, 20))
        self.LikedPhotoLabel.setMinimumSize(QtCore.QSize(41, 20))
        self.LikedPhotoLabel.setMaximumSize(QtCore.QSize(41, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.LikedPhotoLabel.setFont(font)
        self.LikedPhotoLabel.setStyleSheet("color: rgb(255, 255, 255);")
        self.LikedPhotoLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.LikedPhotoLabel.setObjectName("LikedPhotoLabel")
        self.ComentLabel = QtWidgets.QLabel(self.widget)
        self.ComentLabel.setGeometry(QtCore.QRect(495, 640, 41, 20))
        self.ComentLabel.setMinimumSize(QtCore.QSize(41, 20))
        self.ComentLabel.setMaximumSize(QtCore.QSize(41, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ComentLabel.setFont(font)
        self.ComentLabel.setStyleSheet("color: rgb(255, 255, 255);")
        self.ComentLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ComentLabel.setObjectName("ComentLabel")
        self.CloseButton = QtWidgets.QToolButton(self.widget)
        self.CloseButton.setGeometry(QtCore.QRect(550, 20, 16, 16))
        self.CloseButton.setMinimumSize(QtCore.QSize(16, 16))
        self.CloseButton.setMaximumSize(QtCore.QSize(16, 16))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(7)
        font.setBold(False)
        font.setWeight(50)
        self.CloseButton.setFont(font)
        self.CloseButton.setToolTipDuration(1)
        self.CloseButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.CloseButton.setStyleSheet("background-color: rgb(255, 96, 92);\n"
"image: url(:/ex/close.png);\n"
"border-radius:8px;\n"
"")
        self.CloseButton.setText("")
        self.CloseButton.setIconSize(QtCore.QSize(25, 25))
        self.CloseButton.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.CloseButton.setAutoRaise(False)
        self.CloseButton.setObjectName("CloseButton")
        self.minimaliseButton = QtWidgets.QToolButton(self.widget)
        self.minimaliseButton.setGeometry(QtCore.QRect(530, 20, 16, 16))
        self.minimaliseButton.setMinimumSize(QtCore.QSize(16, 16))
        self.minimaliseButton.setMaximumSize(QtCore.QSize(16, 16))
        self.minimaliseButton.setStyleSheet("background-color: rgb(255, 189, 68);\n"
"image: url(:/min/minimize.png);\n"
"border-radius:8px;\n"
"")
        self.minimaliseButton.setText("")
        self.minimaliseButton.setIconSize(QtCore.QSize(25, 25))
        self.minimaliseButton.setObjectName("minimaliseButton")
        self.label_29 = QtWidgets.QLabel(self.widget)
        self.label_29.setGeometry(QtCore.QRect(30, 580, 81, 20))
        self.label_29.setMinimumSize(QtCore.QSize(81, 20))
        self.label_29.setMaximumSize(QtCore.QSize(81, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_29.setFont(font)
        self.label_29.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_29.setObjectName("label_29")
        self.WhoIsLogin = QtWidgets.QLabel(self.widget)
        self.WhoIsLogin.setGeometry(QtCore.QRect(120, 580, 81, 20))
        self.WhoIsLogin.setMinimumSize(QtCore.QSize(81, 20))
        self.WhoIsLogin.setMaximumSize(QtCore.QSize(81, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.WhoIsLogin.setFont(font)
        self.WhoIsLogin.setStyleSheet("color: rgb(255, 255, 255);")
        self.WhoIsLogin.setAlignment(QtCore.Qt.AlignCenter)
        self.WhoIsLogin.setObjectName("WhoIsLogin")
        self.label_30 = QtWidgets.QLabel(self.widget)
        self.label_30.setGeometry(QtCore.QRect(30, 610, 81, 20))
        self.label_30.setMinimumSize(QtCore.QSize(81, 20))
        self.label_30.setMaximumSize(QtCore.QSize(81, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_30.setFont(font)
        self.label_30.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_30.setObjectName("label_30")
        self.HowMuchDays = QtWidgets.QLabel(self.widget)
        self.HowMuchDays.setGeometry(QtCore.QRect(120, 610, 81, 20))
        self.HowMuchDays.setMinimumSize(QtCore.QSize(81, 20))
        self.HowMuchDays.setMaximumSize(QtCore.QSize(81, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.HowMuchDays.setFont(font)
        self.HowMuchDays.setStyleSheet("color: rgb(255, 255, 255);")
        self.HowMuchDays.setAlignment(QtCore.Qt.AlignCenter)
        self.HowMuchDays.setObjectName("HowMuchDays")
        self.Ver = QtWidgets.QLabel(self.widget)
        self.Ver.setGeometry(QtCore.QRect(50, 20, 51, 16))
        self.Ver.setMinimumSize(QtCore.QSize(51, 16))
        self.Ver.setMaximumSize(QtCore.QSize(51, 16))
        self.Ver.setStyleSheet("border-radius:5px;\n"
"background-color: rgb(79, 74, 84);\n"
"color: rgb(255, 255, 255);")
        self.Ver.setAlignment(QtCore.Qt.AlignCenter)
        self.Ver.setObjectName("Ver")
        self.LoginIGmainLabel_7 = QtWidgets.QLabel(self.widget)
        self.LoginIGmainLabel_7.setGeometry(QtCore.QRect(430, 410, 61, 20))
        self.LoginIGmainLabel_7.setMinimumSize(QtCore.QSize(61, 20))
        self.LoginIGmainLabel_7.setMaximumSize(QtCore.QSize(61, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.LoginIGmainLabel_7.setFont(font)
        self.LoginIGmainLabel_7.setStyleSheet("color: rgb(255, 255, 255);")
        self.LoginIGmainLabel_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.LoginIGmainLabel_7.setFrameShadow(QtWidgets.QFrame.Plain)
        self.LoginIGmainLabel_7.setObjectName("LoginIGmainLabel_7")
        self.DodajKonto = QtWidgets.QToolButton(self.widget)
        self.DodajKonto.setGeometry(QtCore.QRect(390, 430, 141, 23))
        self.DodajKonto.setMinimumSize(QtCore.QSize(141, 23))
        self.DodajKonto.setMaximumSize(QtCore.QSize(141, 23))
        self.DodajKonto.setStyleSheet("border-radius:5px;\n"
"background-color: rgb(79, 74, 84);\n"
"color: rgb(255, 255, 255);")
        self.DodajKonto.setObjectName("DodajKonto")
        self.UnfollowButton = QtWidgets.QToolButton(self.widget)
        self.UnfollowButton.setGeometry(QtCore.QRect(390, 460, 141, 23))
        self.UnfollowButton.setMinimumSize(QtCore.QSize(141, 23))
        self.UnfollowButton.setMaximumSize(QtCore.QSize(141, 23))
        self.UnfollowButton.setStyleSheet("border-radius:5px;\n"
"background-color: rgb(79, 74, 84);\n"
"color: rgb(255, 255, 255);")
        self.UnfollowButton.setObjectName("UnfollowButton")
        self.label_31 = QtWidgets.QLabel(self.widget)
        self.label_31.setGeometry(QtCore.QRect(305, 730, 181, 20))
        self.label_31.setMinimumSize(QtCore.QSize(181, 20))
        self.label_31.setMaximumSize(QtCore.QSize(181, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_31.setFont(font)
        self.label_31.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_31.setObjectName("label_31")
        self.Unfollowed = QtWidgets.QLabel(self.widget)
        self.Unfollowed.setGeometry(QtCore.QRect(495, 730, 41, 20))
        self.Unfollowed.setMinimumSize(QtCore.QSize(41, 20))
        self.Unfollowed.setMaximumSize(QtCore.QSize(41, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Unfollowed.setFont(font)
        self.Unfollowed.setStyleSheet("color: rgb(255, 255, 255);")
        self.Unfollowed.setAlignment(QtCore.Qt.AlignCenter)
        self.Unfollowed.setObjectName("Unfollowed")
        self.label_23 = QtWidgets.QLabel(self.widget)
        self.label_23.setGeometry(QtCore.QRect(50, 420, 81, 21))
        self.label_23.setMinimumSize(QtCore.QSize(81, 21))
        self.label_23.setMaximumSize(QtCore.QSize(81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_23.setObjectName("label_23")
        self.minFollow = QtWidgets.QLineEdit(self.widget)
        self.minFollow.setGeometry(QtCore.QRect(140, 421, 31, 20))
        self.minFollow.setMinimumSize(QtCore.QSize(31, 20))
        self.minFollow.setMaximumSize(QtCore.QSize(31, 20))
        self.minFollow.setStyleSheet("background-color: rgb(79,74,84);\n"
"color: rgb(255, 255, 255);\n"
"border:none;\n"
"border-radius:10px;\n"
"\n"
"")
        self.minFollow.setText("")
        self.minFollow.setMaxLength(2)
        self.minFollow.setAlignment(QtCore.Qt.AlignCenter)
        self.minFollow.setObjectName("minFollow")
        self.maxFollow = QtWidgets.QLineEdit(self.widget)
        self.maxFollow.setGeometry(QtCore.QRect(180, 421, 31, 20))
        self.maxFollow.setMinimumSize(QtCore.QSize(31, 20))
        self.maxFollow.setMaximumSize(QtCore.QSize(31, 20))
        self.maxFollow.setStyleSheet("background-color: rgb(79,74,84);\n"
"color: rgb(255, 255, 255);\n"
"border:none;\n"
"border-radius:10px;\n"
"\n"
"")
        self.maxFollow.setText("")
        self.maxFollow.setMaxLength(2)
        self.maxFollow.setAlignment(QtCore.Qt.AlignCenter)
        self.maxFollow.setObjectName("maxFollow")
        self.BG.raise_()
        self.label.raise_()
        self.LoginIGmainLabel.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.loginEntry.raise_()
        self.passwordEntry.raise_()
        self.saveButton.raise_()
        self.loadButton.raise_()
        self.delButton.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.FirefoxButton.raise_()
        self.Chromebutton.raise_()
        self.label_6.raise_()
        self.LoginIGmainLabel_2.raise_()
        self.IloscKontEntry.raise_()
        self.NazwaKontaEntry.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.FollowersButton.raise_()
        self.label_11.raise_()
        self.NazwaHaszEntry.raise_()
        self.HaszButton.raise_()
        self.LoginIGmainLabel_3.raise_()
        self.label_12.raise_()
        self.label_13.raise_()
        self.IloscHaszKont.raise_()
        self.label_15.raise_()
        self.LoginIGmainLabel_4.raise_()
        self.ComentCheckBox.raise_()
        self.LikeCheckBox.raise_()
        self.label_16.raise_()
        self.label_17.raise_()
        self.FollowButton.raise_()
        self.label_18.raise_()
        self.LoginIGmainLabel_5.raise_()
        self.Message_Button.raise_()
        self.label_9.raise_()
        self.LoginIGmainLabel_6.raise_()
        self.label_19.raise_()
        self.label_10.raise_()
        self.label_20.raise_()
        self.CommentEdit.raise_()
        self.MessageEdit.raise_()
        self.Website.raise_()
        self.label_21.raise_()
        self.label_22.raise_()
        self.timerLabel.raise_()
        self.label_24.raise_()
        self.followCountLabel.raise_()
        self.label_26.raise_()
        self.DownloadedLabel.raise_()
        self.label_27.raise_()
        self.SendedMessage.raise_()
        self.label_25.raise_()
        self.label_28.raise_()
        self.LikedPhotoLabel.raise_()
        self.ComentLabel.raise_()
        self.CloseButton.raise_()
        self.minimaliseButton.raise_()
        self.label_29.raise_()
        self.WhoIsLogin.raise_()
        self.label_30.raise_()
        self.HowMuchDays.raise_()
        self.Ver.raise_()
        self.LoginIGmainLabel_7.raise_()
        self.DodajKonto.raise_()
        self.UnfollowButton.raise_()
        self.label_31.raise_()
        self.Unfollowed.raise_()
        self.label_23.raise_()
        self.minFollow.raise_()
        self.maxFollow.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.loginEntry, self.passwordEntry)
        MainWindow.setTabOrder(self.passwordEntry, self.saveButton)
        MainWindow.setTabOrder(self.saveButton, self.loadButton)
        MainWindow.setTabOrder(self.loadButton, self.delButton)
        MainWindow.setTabOrder(self.delButton, self.FirefoxButton)
        MainWindow.setTabOrder(self.FirefoxButton, self.Chromebutton)
        MainWindow.setTabOrder(self.Chromebutton, self.NazwaKontaEntry)
        MainWindow.setTabOrder(self.NazwaKontaEntry, self.IloscKontEntry)
        MainWindow.setTabOrder(self.IloscKontEntry, self.FollowersButton)
        MainWindow.setTabOrder(self.FollowersButton, self.NazwaHaszEntry)
        MainWindow.setTabOrder(self.NazwaHaszEntry, self.IloscHaszKont)
        MainWindow.setTabOrder(self.IloscHaszKont, self.HaszButton)
        MainWindow.setTabOrder(self.HaszButton, self.ComentCheckBox)
        MainWindow.setTabOrder(self.ComentCheckBox, self.LikeCheckBox)
        MainWindow.setTabOrder(self.LikeCheckBox, self.minFollow)
        MainWindow.setTabOrder(self.minFollow, self.maxFollow)
        MainWindow.setTabOrder(self.maxFollow, self.FollowButton)
        MainWindow.setTabOrder(self.FollowButton, self.Message_Button)
        MainWindow.setTabOrder(self.Message_Button, self.DodajKonto)
        MainWindow.setTabOrder(self.DodajKonto, self.UnfollowButton)
        MainWindow.setTabOrder(self.UnfollowButton, self.Website)
        MainWindow.setTabOrder(self.Website, self.MessageEdit)
        MainWindow.setTabOrder(self.MessageEdit, self.CommentEdit)
        MainWindow.setTabOrder(self.CommentEdit, self.minimaliseButton)
        MainWindow.setTabOrder(self.minimaliseButton, self.CloseButton)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.LoginIGmainLabel.setText(_translate("MainWindow", "Dane do konta IG"))
        self.label_2.setText(_translate("MainWindow", "Login:"))
        self.label_3.setText(_translate("MainWindow", "Hasło:"))
        self.loginEntry.setToolTip(_translate("MainWindow", "<html><head/><body><p>Podaj login do konta Instagram</p></body></html>"))
        self.passwordEntry.setToolTip(_translate("MainWindow", "<html><head/><body><p>Podaj hasło do konta Instagram</p></body></html>"))
        self.saveButton.setText(_translate("MainWindow", "Zapisz Konto"))
        self.loadButton.setText(_translate("MainWindow", "Załaduj Konto"))
        self.delButton.setText(_translate("MainWindow", "Usuń Konto"))
        self.label_4.setText(_translate("MainWindow", "Firefox"))
        self.label_5.setText(_translate("MainWindow", "Chrome"))
        self.LoginIGmainLabel_2.setText(_translate("MainWindow", "Pobierz obserwujących profil"))
        self.IloscKontEntry.setToolTip(_translate("MainWindow", "<html><head/><body><p>Ilość kont które bot ma pobrać</p></body></html>"))
        self.NazwaKontaEntry.setToolTip(_translate("MainWindow", "<html><head/><body><p>Nazwa Konta z którego bot ma wyciągnąć obserwujących</p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "Nazwa Konta:"))
        self.label_8.setText(_translate("MainWindow", "Ilość kont:"))
        self.FollowersButton.setText(_translate("MainWindow", "Uruchom Pobieranie"))
        self.NazwaHaszEntry.setToolTip(_translate("MainWindow", "<html><head/><body><p>Nazwa # z którego bot ma wyciągnąć nazwy użytkownika</p></body></html>"))
        self.HaszButton.setText(_translate("MainWindow", "Uruchom Pobieranie"))
        self.LoginIGmainLabel_3.setText(_translate("MainWindow", "Pobierz konta #"))
        self.label_12.setText(_translate("MainWindow", "#"))
        self.label_13.setText(_translate("MainWindow", "Ilość kont:"))
        self.IloscHaszKont.setToolTip(_translate("MainWindow", "<html><head/><body><p>Ilość kont które bot ma pobrać</p></body></html>"))
        self.LoginIGmainLabel_4.setText(_translate("MainWindow", "Obserwacja z Pliku"))
        self.label_16.setText(_translate("MainWindow", "Dodaj komentarz"))
        self.label_17.setText(_translate("MainWindow", "Polub zdjęcie"))
        self.FollowButton.setText(_translate("MainWindow", "Uruchom Obserowanie"))
        self.LoginIGmainLabel_5.setText(_translate("MainWindow", "Wyślij Wiadomość"))
        self.Message_Button.setText(_translate("MainWindow", "Uruchom Rozmowe"))
        self.LoginIGmainLabel_6.setText(_translate("MainWindow", "INFORMACJE"))
        self.label_19.setText(_translate("MainWindow", "Status:"))
        self.label_20.setText(_translate("MainWindow", "Nieaktywny"))
        self.CommentEdit.setToolTip(_translate("MainWindow", "<html><head/><body><p>Edytuj komentarze które bot ma ummieszczać</p></body></html>"))
        self.CommentEdit.setText(_translate("MainWindow", "Edytuj Komentarze"))
        self.MessageEdit.setToolTip(_translate("MainWindow", "<html><head/><body><p>Edytuj wiadomość która ma zostać wysłana do użytkowników</p></body></html>"))
        self.MessageEdit.setText(_translate("MainWindow", "Edytuj Wiadomości"))
        self.Website.setText(_translate("MainWindow", "Kontakt z Nami"))
        self.label_21.setText(_translate("MainWindow", "© Daniel Zieliński, Artur Kaczuba, Łukasz Mela 2021."))
        self.label_22.setText(_translate("MainWindow", "Do następnej sesji zostało:"))
        self.timerLabel.setText(_translate("MainWindow", "0s"))
        self.label_24.setText(_translate("MainWindow", "Zaobserwowanych:"))
        self.followCountLabel.setText(_translate("MainWindow", "0"))
        self.label_26.setText(_translate("MainWindow", "Pobranych Nazw Kont:"))
        self.DownloadedLabel.setText(_translate("MainWindow", "0"))
        self.label_27.setText(_translate("MainWindow", "Wysłano wiadomości:"))
        self.SendedMessage.setText(_translate("MainWindow", "0"))
        self.label_25.setText(_translate("MainWindow", "Dodanych Komentarzy:"))
        self.label_28.setText(_translate("MainWindow", "Polubionych Zdjęć:"))
        self.LikedPhotoLabel.setText(_translate("MainWindow", "0"))
        self.ComentLabel.setText(_translate("MainWindow", "0"))
        self.label_29.setText(_translate("MainWindow", "Zalogowany:"))
        self.WhoIsLogin.setText(_translate("MainWindow", "TESTER"))
        self.label_30.setText(_translate("MainWindow", "Pozostało:"))
        self.HowMuchDays.setText(_translate("MainWindow", "999 Dni"))
        self.Ver.setToolTip(_translate("MainWindow", "<html><head/><body>"+verInfo+"</body></html>"))
        self.Ver.setText(_translate("MainWindow", ver))
        self.LoginIGmainLabel_7.setText(_translate("MainWindow", "Unfollow"))
        self.DodajKonto.setText(_translate("MainWindow", "Zapisz Konta"))
        self.UnfollowButton.setText(_translate("MainWindow", "Uruchom Unfollow"))
        self.label_31.setText(_translate("MainWindow", "Odobserowanych:"))
        self.Unfollowed.setText(_translate("MainWindow", "0"))
        self.label_23.setText(_translate("MainWindow", "Ilość Follow"))
        self.minFollow.setToolTip(_translate("MainWindow", "<html><head/><body><p>Minimalna wartośc to 3</p></body></html>"))
        self.minFollow.setPlaceholderText(_translate("MainWindow", "Od"))
        self.maxFollow.setToolTip(_translate("MainWindow", "<html><head/><body><p>Maksymalna wartość to 30</p></body></html>"))
        self.maxFollow.setPlaceholderText(_translate("MainWindow", "Do"))
import res


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
